name: Build APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21.0.7'
        distribution: 'oracle'
        architecture: 'x64'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: quick-browser-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Release APK (if not PR)
      if: github.event_name != 'pull_request'
      run: ./gradlew assembleRelease
      
    - name: Upload Release APK (if not PR)
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: quick-browser-release
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 30